#!/bin/bash
export CC="gcc"
export CFLAGS="-O2 -Wall -fvisibility=hidden -flto -DZEPHIR_RELEASE=1"
if [ -f Makefile ]; then
	make clean
	/home/work/php/bin/phpize --clean
fi
/home/work/php/bin/phpize 
./configure --enable-beeframework --with-php-config=/home/work/php/bin/php-config
make && make  install
